### ISSUE TITLE
SelectBoxIt v4.0.0 Roadmap

### ISSUE THREAD

**Issue by gfranko** [gfranko/jquery.selectBoxIt.js#109]
# New Features
- [ ] Rewrite SelectBoxIt using [jqfactory](https://github.com/gfranko/jqfactory)
- [ ] Provide optional support for **custom scrollbars** (this might already be possible with existing libraries)
- [ ] Support optional support for the `multiple` attribute. The UI will look similar to the current select box specification for multiple selection select boxes.
##

**Comment by thekrotek** [comment]
Wow, 2 years passed and still no support for multiple attribute. Looks like this project as abandoned. Very sad.

**Comment by gfranko** [comment]
@thekrotek =(

**Comment by ekaj03** [comment]
Is there an update already for the multiple select feature?
