### ISSUE TITLE
SelectBoxIt v3.2.0 Roadmap

### ISSUE THREAD

**Issue by gfranko** [gfranko/jquery.selectBoxIt.js#123]
# New Features
- [x] Add a **nativeMousdown** option to mimic the native firefox drop down behavior by opening the drop down on mousedown and being able to select the currently hovered drop down option on `mouseup` #89 
- [x] Add a **copyClasses** option to allow a user to specify if they would like a select box class(s) to be copied over to the drop down container (which holds both the drop down button and drop down list) or the drop down button. #124 @ronlussier 
- [x] Add a **customShowHideEvent** option to which prevents a drop down from opening on `click` or `mousedown`, which allows a user to open/close the drop down with a custom event handler. #89 
# Bug Fixes
- [x] The **dynamic positioning** behavior seems to not be working until the second time the drop down is opened/clicked.
- [x] The `bootstrap` theme has an issue when the drop down list is dynamically positioned on top of the drop down button, allowing a user to accidentally select a different option than he or she meant to select.  The culprit is the bootstrap `box-shadow` property and should be removed.
- [x] Mobile webkit does not correctly increase a select box element's height, causing bigger mobile select box's to open the desktop drop down menu by accident.  We should add the `-webkit-appearance: menulist-button;` CSS property to the native select box to make sure the height is correctly increased.
- [x] Make the `refresh()` method compatible with the **native** option #125 
- [x]  Prevent the  `open()`, and `close()` methods from opening the desktop drop down list with mobile devices
