### ISSUE TITLE
SelectBoxIt v3.4.0 Roadmap

### ISSUE THREAD

**Issue by gfranko** [gfranko/jquery.selectBoxIt.js#138]
# New Features
- [x] Create a `populate()` convenience method/option that accepts JSON data, an array, a single object, or valid HTML string.  This should make it easy to create a drop down using an ajax call or external data source.
- [x] Create a `add()` convenience method that accepts JSON data, an array, a single object, or valid HTML string.  This should make it easy to dynamically add options to a drop down.
- [x] Create a `remove()` convenience method that accepts a number or an array of numbers.  This should make it easy to dynamically remove options from a drop down.
- [x] Remove all tagNames from the CSS
-  [x] Copy `optgroup` class names over
# Bug Fixes
- [x] Update `disabled` CSS styles
