### ISSUE TITLE
SelectBoxIt v3.0.0 Roadmap

### ISSUE THREAD

**Issue by gfranko** [gfranko/jquery.selectBoxIt.js#91]
# Refactoring and Performance
- [x] Refactor **jquery.selectBoxIt.core.js** and split out as much functionality as possible into different files
- [x] Refactor the grunt build process to remove the IIFE's within each optional file (should save ~1kb off total file size) and only minify **jquery.selectBoxIt.js**.
- [x] Remove all switch statements #108 
- [x] Improve search algorithm accuracy for long lists #110 
- [x] Remove as many dynamic CSS style declarations from the JavaScript as possible.
- [x] Fix mobile positioning bug
# New, Upgraded, and Removed Options
- [x] Add a new **copyAttributes** option to allow a user to specify which HTML attributes they would like copied over to the new drop down.
- [x] Add a new **viewport** option to constrain the dropdown list to the dimensions of an element other than the window
- [x] Add a new **similarSearch** option to optimize for lists with similar values (i.e. State list) 
- [x] Build out a brand new custom CSS **theme** and use it as the default theme.  This theme will model the Twitter Bootstrap theme, but will allow user's to not have to include the Twitter Bootstrap CSS file.
- [x] Remove the **nostyle** option, since this is no longer needed because there is no dynamic JS styling
# Custom Web Build
- [x] Upgrade the custom web build process with any new changes to the grunt build (added files, etc), and use the Google Closure Compiler to allow the custom web build process to provide users with minified and/or unminified versions of SelectBoxIt. #106 
# Unit Testing
- [x] Write more Jasmine tests
# Support
- [x] Officially drop **IE7 support**
- [x] Update documentation on the website

**Note:** The current state of the 3.0 release can be found in the _dev_ branch
